{{
  config(
    materialized='incremental',
    schema= 'staging',
    sort= 'STG_SEGMENT_IDENTIFY_KEY'
  )
}}

with identify as
(
    SELECT
         STG_SEGMENT_IDENTIFY_KEY
        ,SRC_SEGMENT_IDENTIFY_KEY
        ,CAST( NVL2(ENR_COMPANY_SCN_ID,TRUE,FALSE) AS BOOLEAN) GOT_COMPANY_SCN_FLAG
        ,CAST( NVL2(TRA_COMPANY_NAME_UPPER,TRUE,FALSE) AS BOOLEAN) GOT_TRA_COMPANY_FLAG
        ,CAST( NVL2(TRA_CLEARBIT_COMPANY_LEGAL_NAME_UPPER,TRUE,FALSE) AS BOOLEAN) GOT_TRA_CLEARBIT_FLAG
        ,CAST( NVL2(TRA_CLEARBIT_REVEAL_COMPANY_LEGAL_NAME_UPPER,TRUE,FALSE) AS BOOLEAN) GOT_TRA_CLEARBIT_REVEAL_FLAG
        ,TRA_CLEARBIT_REVEAL_FLAG
        ,TRA_CLEARBIT_FLAG
        ,ENR_COMPANY_FLAG
        ,ENR_COMPANY_SCN_ID
        ,ENR_COMPANY_SCN
        ,ENR_COMPANY_SCN_UPPER
        ,ENR_COMPANY_SUBMITTED
        ,ENR_COMPANY_VALIDATED_TS
        ,ENR_COMPANY_VERDICT
        ,ENR_COMPANY_DOMAIN_SUBMITTED
        ,TRA_COMPANY_NAME
        ,TRA_COMPANY_NAME_UPPER
        ,TRA_CLEARBIT_COMPANY_CATEGORY_INDUSTRY
        ,TRA_CLEARBIT_COMPANY_CATEGORY_INDUSTRY_GROUP
        ,TRA_CLEARBIT_COMPANY_CATEGORY_SECTOR
        ,TRA_CLEARBIT_COMPANY_DOMAIN
        ,TRA_CLEARBIT_COMPANY_LEGAL_NAME
        ,TRA_CLEARBIT_COMPANY_LEGAL_NAME_UPPER
        ,TRA_CLEARBIT_COMPANY_METRICS_ANNUAL_REVENUE
        ,TRA_CLEARBIT_COMPANY_METRICS_EMPLOYEES
        ,TRA_CLEARBIT_COMPANY_METRICS_EMPLOYEES_RANGE
        ,TRA_CLEARBIT_COMPANY_METRICS_ESTIMATED_ANNUAL_REVENUE
        ,TRA_CLEARBIT_COMPANY_NAME
        ,TRA_CLEARBIT_COMPANY_NAME_UPPER
        ,TRA_CLEARBIT_REVEAL_COMPANY_LEGAL_NAME
        ,TRA_CLEARBIT_REVEAL_COMPANY_LEGAL_NAME_UPPER
        ,CONTEXT
        ,TRAITS
        ,ORIGINAL
        ,ENRICHMENT
        ,TIMESTAMP
        ,SOURCE_SYSTEM
        ,ANONYMOUSID
        ,USERID
        ,EMAIL
    FROM  DEMO_STAGING.STG_SEGMENT_IDENTIFY
    WHERE  (  
               TRA_CLEARBIT_FLAG = 'TRUE'
            OR ENR_COMPANY_FLAG = 'TRUE'
            )
            AND ( ENR_COMPANY_SUBMITTED IS NOT NULL
                OR ENR_COMPANY_SCN IS NOT NULL
            )
    ORDER BY {{ ref('stg_segment_identify') }} 
)

SELECT * FROM identify

{% if is_incremental() %}

  -- this filter will only be applied on an incremental run
  where STG_SEGMENT_IDENTIFY_KEY > (select max(STG_SEGMENT_IDENTIFY_KEY) from {{ this }})

{% endif %}